version: '3.8'
services:
  apache:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - .apache/siteAva/:/etc/apache2/sites-available
      - .apache/siteEnab/:etc/apache2/sites-enabled
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: lamp_user
      WORDPRESS_DB_PASSWORD: lamp_password
      WORDPRESS_DB_NAME: lamp_db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: lamp_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
