services:
  apache:
    image: wordpress:latest
    container_name: wordpress
    command: bash -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: lamp_user
      WORDPRESS_DB_PASSWORD: lamp_password
      WORDPRESS_DB_NAME: lamp_db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: lamp_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - apache

volumes:
  db_data:
